// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.19.4
// source: behavior.proto

package behavior

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Behavior 行为数据实体
type Behavior struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                // 行为数据ID
	Key       string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`                               // 行为标识键
	UserId    int64  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // 用户ID
	Data      string `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`                             // 行为数据（JSON格式）
	CreatedAt int64  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // 创建时间戳（毫秒）
	UpdatedAt int64  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // 更新时间戳（毫秒）
}

func (x *Behavior) Reset() {
	*x = Behavior{}
	if protoimpl.UnsafeEnabled {
		mi := &file_behavior_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Behavior) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Behavior) ProtoMessage() {}

func (x *Behavior) ProtoReflect() protoreflect.Message {
	mi := &file_behavior_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Behavior.ProtoReflect.Descriptor instead.
func (*Behavior) Descriptor() ([]byte, []int) {
	return file_behavior_proto_rawDescGZIP(), []int{0}
}

func (x *Behavior) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Behavior) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Behavior) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Behavior) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Behavior) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Behavior) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// RecordBehaviorRequest 记录行为数据请求
type RecordBehaviorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`                      // 行为标识键
	UserId int64  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	Data   string `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                    // 行为数据（JSON格式）
}

func (x *RecordBehaviorRequest) Reset() {
	*x = RecordBehaviorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_behavior_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordBehaviorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordBehaviorRequest) ProtoMessage() {}

func (x *RecordBehaviorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_behavior_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordBehaviorRequest.ProtoReflect.Descriptor instead.
func (*RecordBehaviorRequest) Descriptor() ([]byte, []int) {
	return file_behavior_proto_rawDescGZIP(), []int{1}
}

func (x *RecordBehaviorRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RecordBehaviorRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RecordBehaviorRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// RecordBehaviorResponse 记录行为数据响应
type RecordBehaviorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool  `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 记录是否成功
	Id      int64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`           // 新创建的行为数据ID（可选）
}

func (x *RecordBehaviorResponse) Reset() {
	*x = RecordBehaviorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_behavior_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecordBehaviorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordBehaviorResponse) ProtoMessage() {}

func (x *RecordBehaviorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_behavior_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordBehaviorResponse.ProtoReflect.Descriptor instead.
func (*RecordBehaviorResponse) Descriptor() ([]byte, []int) {
	return file_behavior_proto_rawDescGZIP(), []int{2}
}

func (x *RecordBehaviorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RecordBehaviorResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// BatchRecordBehaviorRequest 批量记录行为数据请求
type BatchRecordBehaviorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Behaviors []*RecordBehaviorRequest `protobuf:"bytes,1,rep,name=behaviors,proto3" json:"behaviors,omitempty"` // 行为数据列表
}

func (x *BatchRecordBehaviorRequest) Reset() {
	*x = BatchRecordBehaviorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_behavior_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchRecordBehaviorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRecordBehaviorRequest) ProtoMessage() {}

func (x *BatchRecordBehaviorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_behavior_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRecordBehaviorRequest.ProtoReflect.Descriptor instead.
func (*BatchRecordBehaviorRequest) Descriptor() ([]byte, []int) {
	return file_behavior_proto_rawDescGZIP(), []int{3}
}

func (x *BatchRecordBehaviorRequest) GetBehaviors() []*RecordBehaviorRequest {
	if x != nil {
		return x.Behaviors
	}
	return nil
}

// BatchRecordBehaviorResponse 批量记录行为数据响应
type BatchRecordBehaviorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SuccessCount int64                     `protobuf:"varint,1,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"` // 成功记录数量
	FailCount    int64                     `protobuf:"varint,2,opt,name=fail_count,json=failCount,proto3" json:"fail_count,omitempty"`          // 失败记录数量
	SuccessList  []*RecordBehaviorResponse `protobuf:"bytes,3,rep,name=success_list,json=successList,proto3" json:"success_list,omitempty"`     // 成功记录列表
	FailList     []*RecordBehaviorRequest  `protobuf:"bytes,4,rep,name=fail_list,json=failList,proto3" json:"fail_list,omitempty"`              // 失败记录列表
}

func (x *BatchRecordBehaviorResponse) Reset() {
	*x = BatchRecordBehaviorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_behavior_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchRecordBehaviorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRecordBehaviorResponse) ProtoMessage() {}

func (x *BatchRecordBehaviorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_behavior_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRecordBehaviorResponse.ProtoReflect.Descriptor instead.
func (*BatchRecordBehaviorResponse) Descriptor() ([]byte, []int) {
	return file_behavior_proto_rawDescGZIP(), []int{4}
}

func (x *BatchRecordBehaviorResponse) GetSuccessCount() int64 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *BatchRecordBehaviorResponse) GetFailCount() int64 {
	if x != nil {
		return x.FailCount
	}
	return 0
}

func (x *BatchRecordBehaviorResponse) GetSuccessList() []*RecordBehaviorResponse {
	if x != nil {
		return x.SuccessList
	}
	return nil
}

func (x *BatchRecordBehaviorResponse) GetFailList() []*RecordBehaviorRequest {
	if x != nil {
		return x.FailList
	}
	return nil
}

// GetBehaviorRequest 获取行为数据请求
type GetBehaviorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 行为数据ID
}

func (x *GetBehaviorRequest) Reset() {
	*x = GetBehaviorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_behavior_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBehaviorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBehaviorRequest) ProtoMessage() {}

func (x *GetBehaviorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_behavior_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBehaviorRequest.ProtoReflect.Descriptor instead.
func (*GetBehaviorRequest) Descriptor() ([]byte, []int) {
	return file_behavior_proto_rawDescGZIP(), []int{5}
}

func (x *GetBehaviorRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// ListBehaviorsRequest 分页查询行为数据请求
type ListBehaviorsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page      int32  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                            // 页码（从1开始）
	PageSize  int32  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`    // 每页数量
	Key       string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`                               // 行为标识键（可选）
	UserId    int64  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // 用户ID（可选）
	StartTime int64  `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // 开始时间戳（可选）
	EndTime   int64  `protobuf:"varint,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // 结束时间戳（可选）
}

func (x *ListBehaviorsRequest) Reset() {
	*x = ListBehaviorsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_behavior_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBehaviorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBehaviorsRequest) ProtoMessage() {}

func (x *ListBehaviorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_behavior_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBehaviorsRequest.ProtoReflect.Descriptor instead.
func (*ListBehaviorsRequest) Descriptor() ([]byte, []int) {
	return file_behavior_proto_rawDescGZIP(), []int{6}
}

func (x *ListBehaviorsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBehaviorsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListBehaviorsRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ListBehaviorsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListBehaviorsRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ListBehaviorsRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

// ListBehaviorsResponse 分页查询行为数据响应
type ListBehaviorsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*Behavior `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`    // 行为数据列表
	Total int64       `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 总数量
	Page  int32       `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`   // 当前页码
	Size  int32       `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`   // 每页数量
}

func (x *ListBehaviorsResponse) Reset() {
	*x = ListBehaviorsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_behavior_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBehaviorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBehaviorsResponse) ProtoMessage() {}

func (x *ListBehaviorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_behavior_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBehaviorsResponse.ProtoReflect.Descriptor instead.
func (*ListBehaviorsResponse) Descriptor() ([]byte, []int) {
	return file_behavior_proto_rawDescGZIP(), []int{7}
}

func (x *ListBehaviorsResponse) GetList() []*Behavior {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ListBehaviorsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListBehaviorsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBehaviorsResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// DeleteBehaviorRequest 删除行为数据请求
type DeleteBehaviorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 行为数据ID
}

func (x *DeleteBehaviorRequest) Reset() {
	*x = DeleteBehaviorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_behavior_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBehaviorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBehaviorRequest) ProtoMessage() {}

func (x *DeleteBehaviorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_behavior_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBehaviorRequest.ProtoReflect.Descriptor instead.
func (*DeleteBehaviorRequest) Descriptor() ([]byte, []int) {
	return file_behavior_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteBehaviorRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// DeleteBehaviorResponse 删除行为数据响应
type DeleteBehaviorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 删除是否成功
}

func (x *DeleteBehaviorResponse) Reset() {
	*x = DeleteBehaviorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_behavior_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteBehaviorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBehaviorResponse) ProtoMessage() {}

func (x *DeleteBehaviorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_behavior_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBehaviorResponse.ProtoReflect.Descriptor instead.
func (*DeleteBehaviorResponse) Descriptor() ([]byte, []int) {
	return file_behavior_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteBehaviorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// BatchDeleteBehaviorRequest 批量删除行为数据请求
type BatchDeleteBehaviorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"` // 行为数据ID列表
}

func (x *BatchDeleteBehaviorRequest) Reset() {
	*x = BatchDeleteBehaviorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_behavior_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchDeleteBehaviorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeleteBehaviorRequest) ProtoMessage() {}

func (x *BatchDeleteBehaviorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_behavior_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDeleteBehaviorRequest.ProtoReflect.Descriptor instead.
func (*BatchDeleteBehaviorRequest) Descriptor() ([]byte, []int) {
	return file_behavior_proto_rawDescGZIP(), []int{10}
}

func (x *BatchDeleteBehaviorRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

// BatchDeleteBehaviorResponse 批量删除行为数据响应
type BatchDeleteBehaviorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeletedCount int64   `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"` // 删除成功数量
	FailedIds    []int64 `protobuf:"varint,2,rep,packed,name=failed_ids,json=failedIds,proto3" json:"failed_ids,omitempty"`   // 删除失败的ID列表
}

func (x *BatchDeleteBehaviorResponse) Reset() {
	*x = BatchDeleteBehaviorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_behavior_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchDeleteBehaviorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeleteBehaviorResponse) ProtoMessage() {}

func (x *BatchDeleteBehaviorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_behavior_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDeleteBehaviorResponse.ProtoReflect.Descriptor instead.
func (*BatchDeleteBehaviorResponse) Descriptor() ([]byte, []int) {
	return file_behavior_proto_rawDescGZIP(), []int{11}
}

func (x *BatchDeleteBehaviorResponse) GetDeletedCount() int64 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

func (x *BatchDeleteBehaviorResponse) GetFailedIds() []int64 {
	if x != nil {
		return x.FailedIds
	}
	return nil
}

var File_behavior_proto protoreflect.FileDescriptor

var file_behavior_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x22, 0x97, 0x01, 0x0a, 0x08, 0x42,
	0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x22, 0x56, 0x0a, 0x15, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x42, 0x65,
	0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x42, 0x0a, 0x16,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x5b, 0x0a, 0x1a, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x42,
	0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d,
	0x0a, 0x09, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x52, 0x09, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x73, 0x22, 0xe4, 0x01,
	0x0a, 0x1b, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x42, 0x65, 0x68,
	0x61, 0x76, 0x69, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a,
	0x0d, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x61, 0x69, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x66, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x43, 0x0a, 0x0c, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69,
	0x6f, 0x72, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0b, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x09, 0x66, 0x61, 0x69, 0x6c, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x62, 0x65, 0x68, 0x61,
	0x76, 0x69, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x42, 0x65, 0x68, 0x61, 0x76,
	0x69, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x08, 0x66, 0x61, 0x69, 0x6c,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x24, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x42, 0x65, 0x68, 0x61, 0x76,
	0x69, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0xac, 0x01, 0x0a, 0x14, 0x4c,
	0x69, 0x73, 0x74, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19,
	0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x7d, 0x0a, 0x15, 0x4c, 0x69, 0x73,
	0x74, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e, 0x42, 0x65, 0x68, 0x61,
	0x76, 0x69, 0x6f, 0x72, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x27, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x32, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x65, 0x68, 0x61, 0x76,
	0x69, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x2e, 0x0a, 0x1a, 0x42, 0x61, 0x74, 0x63, 0x68, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03,
	0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x61, 0x0a, 0x1b, 0x42, 0x61, 0x74, 0x63, 0x68, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x61, 0x69,
	0x6c, 0x65, 0x64, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x09, 0x66,
	0x61, 0x69, 0x6c, 0x65, 0x64, 0x49, 0x64, 0x73, 0x32, 0x96, 0x04, 0x0a, 0x0f, 0x62, 0x65, 0x68,
	0x61, 0x76, 0x69, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x53, 0x0a, 0x0e,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x12, 0x1f,
	0x2e, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x20, 0x2e, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x62, 0x0a, 0x13, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x12, 0x24, 0x2e, 0x62, 0x65, 0x68, 0x61, 0x76,
	0x69, 0x6f, 0x72, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x42,
	0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25,
	0x2e, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x42, 0x65, 0x68, 0x61,
	0x76, 0x69, 0x6f, 0x72, 0x12, 0x1c, 0x2e, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e,
	0x47, 0x65, 0x74, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x12, 0x2e, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e, 0x42, 0x65,
	0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x12, 0x50, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x65,
	0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x73, 0x12, 0x1e, 0x2e, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69,
	0x6f, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69,
	0x6f, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x12, 0x1f, 0x2e, 0x62, 0x65, 0x68,
	0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x65, 0x68, 0x61,
	0x76, 0x69, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x62, 0x65,
	0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x65, 0x68,
	0x61, 0x76, 0x69, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x62, 0x0a,
	0x13, 0x42, 0x61, 0x74, 0x63, 0x68, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x65, 0x68, 0x61,
	0x76, 0x69, 0x6f, 0x72, 0x12, 0x24, 0x2e, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x65, 0x68, 0x61, 0x76,
	0x69, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x62, 0x65, 0x68,
	0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x42, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_behavior_proto_rawDescOnce sync.Once
	file_behavior_proto_rawDescData = file_behavior_proto_rawDesc
)

func file_behavior_proto_rawDescGZIP() []byte {
	file_behavior_proto_rawDescOnce.Do(func() {
		file_behavior_proto_rawDescData = protoimpl.X.CompressGZIP(file_behavior_proto_rawDescData)
	})
	return file_behavior_proto_rawDescData
}

var file_behavior_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_behavior_proto_goTypes = []any{
	(*Behavior)(nil),                    // 0: behavior.Behavior
	(*RecordBehaviorRequest)(nil),       // 1: behavior.RecordBehaviorRequest
	(*RecordBehaviorResponse)(nil),      // 2: behavior.RecordBehaviorResponse
	(*BatchRecordBehaviorRequest)(nil),  // 3: behavior.BatchRecordBehaviorRequest
	(*BatchRecordBehaviorResponse)(nil), // 4: behavior.BatchRecordBehaviorResponse
	(*GetBehaviorRequest)(nil),          // 5: behavior.GetBehaviorRequest
	(*ListBehaviorsRequest)(nil),        // 6: behavior.ListBehaviorsRequest
	(*ListBehaviorsResponse)(nil),       // 7: behavior.ListBehaviorsResponse
	(*DeleteBehaviorRequest)(nil),       // 8: behavior.DeleteBehaviorRequest
	(*DeleteBehaviorResponse)(nil),      // 9: behavior.DeleteBehaviorResponse
	(*BatchDeleteBehaviorRequest)(nil),  // 10: behavior.BatchDeleteBehaviorRequest
	(*BatchDeleteBehaviorResponse)(nil), // 11: behavior.BatchDeleteBehaviorResponse
}
var file_behavior_proto_depIdxs = []int32{
	1,  // 0: behavior.BatchRecordBehaviorRequest.behaviors:type_name -> behavior.RecordBehaviorRequest
	2,  // 1: behavior.BatchRecordBehaviorResponse.success_list:type_name -> behavior.RecordBehaviorResponse
	1,  // 2: behavior.BatchRecordBehaviorResponse.fail_list:type_name -> behavior.RecordBehaviorRequest
	0,  // 3: behavior.ListBehaviorsResponse.list:type_name -> behavior.Behavior
	1,  // 4: behavior.behaviorService.RecordBehavior:input_type -> behavior.RecordBehaviorRequest
	3,  // 5: behavior.behaviorService.BatchRecordBehavior:input_type -> behavior.BatchRecordBehaviorRequest
	5,  // 6: behavior.behaviorService.GetBehavior:input_type -> behavior.GetBehaviorRequest
	6,  // 7: behavior.behaviorService.ListBehaviors:input_type -> behavior.ListBehaviorsRequest
	8,  // 8: behavior.behaviorService.DeleteBehavior:input_type -> behavior.DeleteBehaviorRequest
	10, // 9: behavior.behaviorService.BatchDeleteBehavior:input_type -> behavior.BatchDeleteBehaviorRequest
	2,  // 10: behavior.behaviorService.RecordBehavior:output_type -> behavior.RecordBehaviorResponse
	4,  // 11: behavior.behaviorService.BatchRecordBehavior:output_type -> behavior.BatchRecordBehaviorResponse
	0,  // 12: behavior.behaviorService.GetBehavior:output_type -> behavior.Behavior
	7,  // 13: behavior.behaviorService.ListBehaviors:output_type -> behavior.ListBehaviorsResponse
	9,  // 14: behavior.behaviorService.DeleteBehavior:output_type -> behavior.DeleteBehaviorResponse
	11, // 15: behavior.behaviorService.BatchDeleteBehavior:output_type -> behavior.BatchDeleteBehaviorResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_behavior_proto_init() }
func file_behavior_proto_init() {
	if File_behavior_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_behavior_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Behavior); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_behavior_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*RecordBehaviorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_behavior_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*RecordBehaviorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_behavior_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*BatchRecordBehaviorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_behavior_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*BatchRecordBehaviorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_behavior_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetBehaviorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_behavior_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ListBehaviorsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_behavior_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*ListBehaviorsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_behavior_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteBehaviorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_behavior_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteBehaviorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_behavior_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*BatchDeleteBehaviorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_behavior_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*BatchDeleteBehaviorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_behavior_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_behavior_proto_goTypes,
		DependencyIndexes: file_behavior_proto_depIdxs,
		MessageInfos:      file_behavior_proto_msgTypes,
	}.Build()
	File_behavior_proto = out.File
	file_behavior_proto_rawDesc = nil
	file_behavior_proto_goTypes = nil
	file_behavior_proto_depIdxs = nil
}
