// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: behavior.proto

package behaviorservice

import (
	"context"

	"github.com/ziptako/behavior/behavior"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchDeleteBehaviorRequest  = behavior.BatchDeleteBehaviorRequest
	BatchDeleteBehaviorResponse = behavior.BatchDeleteBehaviorResponse
	BatchRecordBehaviorRequest  = behavior.BatchRecordBehaviorRequest
	BatchRecordBehaviorResponse = behavior.BatchRecordBehaviorResponse
	Behavior                    = behavior.Behavior
	DeleteBehaviorRequest       = behavior.DeleteBehaviorRequest
	DeleteBehaviorResponse      = behavior.DeleteBehaviorResponse
	GetBehaviorRequest          = behavior.GetBehaviorRequest
	ListBehaviorsRequest        = behavior.ListBehaviorsRequest
	ListBehaviorsResponse       = behavior.ListBehaviorsResponse
	RecordBehaviorRequest       = behavior.RecordBehaviorRequest
	RecordBehaviorResponse      = behavior.RecordBehaviorResponse

	BehaviorService interface {
		// RecordBehavior 记录行为数据
		RecordBehavior(ctx context.Context, in *RecordBehaviorRequest, opts ...grpc.CallOption) (*RecordBehaviorResponse, error)
		// BatchRecordBehavior 批量记录行为数据
		BatchRecordBehavior(ctx context.Context, in *BatchRecordBehaviorRequest, opts ...grpc.CallOption) (*BatchRecordBehaviorResponse, error)
		// GetBehavior 根据ID获取行为数据详情
		GetBehavior(ctx context.Context, in *GetBehaviorRequest, opts ...grpc.CallOption) (*Behavior, error)
		// ListBehaviors 分页查询行为数据列表
		ListBehaviors(ctx context.Context, in *ListBehaviorsRequest, opts ...grpc.CallOption) (*ListBehaviorsResponse, error)
		// DeleteBehavior 删除行为数据
		DeleteBehavior(ctx context.Context, in *DeleteBehaviorRequest, opts ...grpc.CallOption) (*DeleteBehaviorResponse, error)
		// BatchDeleteBehavior 批量删除行为数据
		BatchDeleteBehavior(ctx context.Context, in *BatchDeleteBehaviorRequest, opts ...grpc.CallOption) (*BatchDeleteBehaviorResponse, error)
	}

	defaultBehaviorService struct {
		cli zrpc.Client
	}
)

func NewBehaviorService(cli zrpc.Client) BehaviorService {
	return &defaultBehaviorService{
		cli: cli,
	}
}

// RecordBehavior 记录行为数据
func (m *defaultBehaviorService) RecordBehavior(ctx context.Context, in *RecordBehaviorRequest, opts ...grpc.CallOption) (*RecordBehaviorResponse, error) {
	client := behavior.NewBehaviorServiceClient(m.cli.Conn())
	return client.RecordBehavior(ctx, in, opts...)
}

// BatchRecordBehavior 批量记录行为数据
func (m *defaultBehaviorService) BatchRecordBehavior(ctx context.Context, in *BatchRecordBehaviorRequest, opts ...grpc.CallOption) (*BatchRecordBehaviorResponse, error) {
	client := behavior.NewBehaviorServiceClient(m.cli.Conn())
	return client.BatchRecordBehavior(ctx, in, opts...)
}

// GetBehavior 根据ID获取行为数据详情
func (m *defaultBehaviorService) GetBehavior(ctx context.Context, in *GetBehaviorRequest, opts ...grpc.CallOption) (*Behavior, error) {
	client := behavior.NewBehaviorServiceClient(m.cli.Conn())
	return client.GetBehavior(ctx, in, opts...)
}

// ListBehaviors 分页查询行为数据列表
func (m *defaultBehaviorService) ListBehaviors(ctx context.Context, in *ListBehaviorsRequest, opts ...grpc.CallOption) (*ListBehaviorsResponse, error) {
	client := behavior.NewBehaviorServiceClient(m.cli.Conn())
	return client.ListBehaviors(ctx, in, opts...)
}

// DeleteBehavior 删除行为数据
func (m *defaultBehaviorService) DeleteBehavior(ctx context.Context, in *DeleteBehaviorRequest, opts ...grpc.CallOption) (*DeleteBehaviorResponse, error) {
	client := behavior.NewBehaviorServiceClient(m.cli.Conn())
	return client.DeleteBehavior(ctx, in, opts...)
}

// BatchDeleteBehavior 批量删除行为数据
func (m *defaultBehaviorService) BatchDeleteBehavior(ctx context.Context, in *BatchDeleteBehaviorRequest, opts ...grpc.CallOption) (*BatchDeleteBehaviorResponse, error) {
	client := behavior.NewBehaviorServiceClient(m.cli.Conn())
	return client.BatchDeleteBehavior(ctx, in, opts...)
}
